import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("paper mode supports adjustable ordered questions and dynamic A4 pagination", async () => {
  const source = await readFile(new URL("../app/paper-mode.tsx", import.meta.url), "utf8");
  const scopePicker = await readFile(new URL("../app/element-scope-picker.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");

  assert.match(source, /type PaperConfig/);
  assert.match(source, /颜色判断/);
  assert.match(source, /物质单选/);
  assert.match(source, /物质多选/);
  assert.match(source, /补全产物/);
  assert.match(source, /补全配平/);
  assert.match(source, /function paginate/);
  assert.match(source, /paginateMeasured/);
  assert.match(source, /useLayoutEffect/);
  assert.match(source, /ResizeObserver/);
  assert.match(source, /paper-measure-body/);
  assert.match(source, /function choiceColumns/);
  assert.match(source, /choices-\$\{columns\}/);
  assert.match(source, /page\}\/{totalPages}/);
  assert.match(source, /SECTION_NUMERALS/);
  assert.match(source, /SECTION_NUMERALS\[sectionIndex\+\+\]/);
  assert.match(source, /addGroup\("判断物质的颜色"/);
  assert.match(source, /addGroup\("根据颜色选择物质"/);
  assert.match(source, /addGroup\("完善化学方程式"/);
  assert.doesNotMatch(source, /page=\{5\}/);
  assert.doesNotMatch(source, /className="paper-border"/);
  assert.doesNotMatch(source, /\[<Formula observation=\{item\.target\} \/>\]/);
  assert.match(source, /\{number\}\.\{"\\t"\}/);
  assert.match(source, /coefficient-blank/);
  assert.match(source, /\{"  "\}/);
  assert.doesNotMatch(source, /\(====\)/);
  assert.match(source, /paper-long-equals/);
  assert.match(source, /equation-stacked/);
  assert.match(source, /sideWidth/);
  assert.match(source, /type ReactionCondition/);
  assert.match(source, /paper-condition/);
  assert.match(source, /paper-participant-marker/);
  assert.match(source, /materialsForElementScope/);
  assert.match(source, /formulaElements\(reaction\.participants/);
  assert.match(source, /data-study-elements=\{reactionStudyElements\}/);
  assert.match(source, /buildAnswerBlocks/);
  assert.match(source, /显示参考答案/);
  assert.match(source, /隐藏参考答案/);
  assert.match(source, /<h1 className="paper-title">参考答案<\/h1>/);
  assert.match(source, /className="paper-answer-table"/);
  assert.match(source, /<th>编号<\/th>/);
  assert.match(source, /<th>答案<\/th>/);
  assert.match(source, /function AnswerEquation/);
  assert.match(source, /paper\.forward, \.\.\.paper\.balanced/);
  assert.match(source, /paper-answer-page/);
  assert.doesNotMatch(source, /paper-answer-page[^\n]*paper-footer/);
  assert.match(source, /ElementScopePicker scope=\{elementScope\}/);
  assert.match(source, /createPaper\(materials, reactions, config, nextScope\)/);
  assert.doesNotMatch(source, /function repeated/);
  assert.match(source, /eligible\.slice\(0, count\)/);
  assert.match(source, /colors\.slice\(0, count\)/);
  assert.match(source, /uniqueBy\(shuffled\(usableReactions/);
  assert.match(source, /reactionPool\.slice\(forward\.length/);
  assert.match(source, /不重复题目，请重新选择考察元素/);
  assert.match(source, /if \(shortage\) \{[\s\S]*?setScopeError\(shortage\);[\s\S]*?return false;/);
  assert.doesNotMatch(source, /item\.target\.name \|\| "物质"/);

  assert.match(scopePicker, /章节多选/);
  assert.match(scopePicker, /自定义周期表/);
  assert.match(scopePicker, /应用范围并重新生成/);
  assert.match(scopePicker, /ALL_ELEMENTS/);
  assert.match(scopePicker, /function elementScopeTitle/);
  assert.match(scopePicker, /元素化学综合测试/);
  assert.match(scopePicker, /chapter\.label\}元素化学测试/);
  assert.match(scopePicker, /配位化学与有色离子测试/);
  assert.match(scopePicker, /元素化学测试（\$\{shown\.join\("、"\)\}/);
  assert.match(source, /const documentTitle = useMemo\(\(\) => elementScopeTitle\(elementScope\)/);
  assert.match(source, /<header className="paper-header">\{title\}<\/header>/);
  assert.doesNotMatch(source, /estimatedWidth/);

  assert.match(styles, /width: 210mm/);
  assert.match(styles, /height: 297mm/);
  assert.match(styles, /font-family: SimSun/);
  assert.match(styles, /font-size: 10\.5pt/);
  assert.match(styles, /font-size: 16pt/);
  assert.match(styles, /font-family: SimHei/);
  assert.match(styles, /\.paper-stem \{ display: grid; grid-template-columns: 2em minmax\(0, 1fr\); padding: 0; text-indent: 0; \}/);
  assert.match(styles, /border-bottom: \.5pt solid #000/);
  assert.match(styles, /\.paper-footer \{[^}]*font-weight: 700/);
  assert.match(styles, /\.paper-question-number \{[\s\S]*?font-family: "Times New Roman", serif;[\s\S]*?font-weight: 700;/);
  assert.match(styles, /\.paper-choices > span > b \{ font-family: "Times New Roman", serif/);
  assert.match(styles, /\.paper-reactants \{ justify-content: flex-start; \}/);
  assert.match(styles, /choices-4 \{ grid-template-columns: repeat\(4/);
  assert.match(styles, /choices-6 \{ grid-template-columns: repeat\(6/);
  assert.match(styles, /width: 4ch/);
  assert.match(styles, /width: 6\.75em/);
  assert.match(styles, /\.equation-stacked \.paper-products \{ flex: 0 0 calc\(100% - 2em\); margin-left: 2em; \}/);
  assert.match(styles, /\.paper-long-equals/);
  assert.match(styles, /\.paper-participant-marker \{ font-family: "Times New Roman", serif; \}/);
  assert.match(styles, /\.paper-transition/);
  assert.match(styles, /\.paper-scope-control/);
  assert.match(styles, /\.paper-answer-page \.paper-body \{ bottom: 13mm; \}/);
  assert.match(styles, /\.paper-answer-table/);
  assert.match(styles, /@page \{ size: A4 portrait; margin: 0; \}/);
  assert.match(styles, /@media print \{[\s\S]*?\.paper-mode \{ padding: 0 !important; background: #fff; \}/);
});
